name: Build WhereMyTunnels

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build_scripts/requirements.txt

      - name: Build
        run: |
          mkdir dist
          python build_scripts/build.py windows --output-path dist/wheremytunnels-windows-x86_64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheremytunnels-windows-x86_64.exe
          path: dist/wheremytunnels-windows-x86_64.exe
          if-no-files-found: error

  build-linux:
    name: Linux (${{ matrix.libc }} / ${{ matrix.architecture }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - libc: "glibc-2.17"
            architecture: "x86_64"
            out_name: "wheremytunnels-linux-x86_64-glibc-2.17.bin"

          - libc: "glibc-2.28"
            architecture: "x86_64"
            out_name: "wheremytunnels-linux-x86_64-glibc-2.28.bin"

          # - libc: "glibc-2.17"
          #   architecture: "aarch64"
          #   out_name: "wheremytunnels-linux-aarch64-glibc-2.17.bin"

          # - libc: "glibc-2.28"
          #   architecture: "aarch64"
          #   out_name: "wheremytunnels-linux-aarch64-glibc-2.28.bin"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Needed for aarch64 builds on x86 GitHub runners in most Docker-based approaches
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build_scripts/requirements.txt

      - name: Build
        run: |
          mkdir -p dist
          python build_scripts/build.py linux \
            --libc "${{ matrix.libc }}" \
            --architecture "${{ matrix.architecture }}" \
            --output-path "dist/${{ matrix.out_name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out_name }}
          path: dist/${{ matrix.out_name }}
          if-no-files-found: error
